### ISSUE TITLE
Support the rest of the Gandi API?

### ISSUE THREAD

**Issue by thommay** [tiramiseb/go-gandi-livedns#5]
Hey,
this module currently is very focussed on the LiveDNS portion of the Gandi API, but the API also supports more rich management of domains, billing and so on. Would you be interested in taking patches to support the rest of the API?

**Comment by tiramiseb** [comment]
Sure, I'd be interested !
I made this package when only LiveDNS existed in the API v5, and never completed it...

**Comment by thommay** [comment]
Great! really I want to be able to terraform our gandi domain management, so that'll be where I end up

**Comment by baloo** [comment]
Hello!
I put some information that I believe you would need to support rest of the api here:
https://github.com/tiramiseb/go-gandi-livedns/pull/6#issuecomment-568202333

**Comment by tiramiseb** [comment]
See https://github.com/tiramiseb/go-gandi :)

@thommay please make your PR against this new repository
